### ISSUE TITLE
CSIDH

### ISSUE THREAD

**Issue by billbuchanan** [cloudflare/circl#104]
I am using Go, I would like to create a demonstrator for CSIDH, and have imported:
    
"github.com/cloudflare/circl/dh/csidh"

but I get the error of:

"module github.com/cloudflare/circl@latest found (v1.0.0), but does not contain package github.com/cloudflare/circl/dh/csidh"

Have I included the import correctly? I can get all the other DH methods to work for Circl, but not for CSIDH.

**Comment by armfazh** [comment]
We are close to make a new release, in the meantime use `github.com/cloudflare/circl@master` for pointing to the get the latest from CIRCL (which is the master branch).

**Comment by billbuchanan** [comment]
Perfect. Works well. I have created a new blog [here](https://medium.com/asecuritysite-when-bob-met-alice/csidh-commutative-sidh-for-fast-post-quantum-key-exchange-5aa61d5aba07?source=friends_link&sk=96a031fd4e1e952cbbbc157e1083190c). If your team have time, please could you check it for technical accuracy?

**Comment by henrydcase** [comment]
In regards technical accuracy, the "So Bob meet Alice" section is related to SIDH, but in case of cSIDH the algorithm works differently. From what I remember it is something like:

In the setup phase, both parties agree on a large prime p of a special form as described above, and the starting elliptic curve E_0 : y^2 = x^3 + x over a finite field F_p as well as integer B.

In the key generation phase, Alice samples from the range of [−B, B], a n-tuple
of integers (each separately). These integers represent ideal class [a] in Cl(O) (it [a] also has a special form, see original research paper). The public key is the coefficient A in F_p of the elliptic curve [a]E_0 : y^2 = x^3 + Ax^2 + x, obtained by applying the action of [a] to the starting, elliptic curve E_0.

The exchange phase starts with Alice and Bob having key pairs ([a], A) and ([b], B).
Upon receipt of a public key from Alice, Bob verifies that the elliptic curve E_A is
supersingular (that what key validation really means in cSIDH). He then applies the action of his secret key [b] to E_A to compute the curve E_R = [b]E_A = [b][a]E_0 . Alice proceeds analogously with hers own secret [a]. The shared secret is the coefficient R of the common secret curve E_R = [a][b]E 0 = [b][a]E 0 , written in the form y^2 = x^3 + Rx^2 + x, which is the same for Alice and Bob due to the commutativity of Cl(O).

But indeed, cSIDH can be swapped easily with classical DH thanks to being fully commutative, so for example it's quite straight forward to build encryption scheme similar to ElGamal (assuming one believes in quantum security from abelian groups).

**Comment by armfazh** [comment]
> Also, what's in your new update?

For example, the dilithium signature scheme.
